### ISSUE TITLE
FR: Override release stage

### ISSUE THREAD

**Issue by adamj88** [bugsnag/bugsnag-magento#1]
At current the module uses `Mage:: getIsDeveloperMode()` to determine what release stage to push to Bugsnag. See: https://github.com/bugsnag/bugsnag-magento/blob/master/src/app/code/community/Bugsnag/Notifier/Model/Observer.php#L75-L78

We have several stages before a Magento store goes to production. Would it be possible to add a text field so to the admin section so that we can override this setting?

**Comment by ConradIrwin** [comment]
@adamj88 certainly! We'll try and get round to this soon, but if you want to send a pull request it would be greatly appreciated :).

**Comment by jonasvanderhaegen** [comment]
@ConradIrwin Hello Conrad, is there any update on this?

**Comment by uni-t** [comment]
Why not make the `releaseStage()` function in the Observer class `protected` instead of `private`, so we can rewrite the class and use our own implementation to figure out the environment?

**Comment by shineability** [comment]
Overriding the release stage should be possible when #6 is merged.
When merged, can you guys also have the package updated on packages.firegento.com?

**Comment by shineability** [comment]
Any update on this?

**Comment by luke-belton** [comment]
`bugsnag-magento` has been deprecated.
