### ISSUE TITLE
Fatal error on Observer::addUserTab() if customer object not in session

### ISSUE THREAD

**Issue by allieshq** [bugsnag/bugsnag-magento#9]
### Expected behavior
`Bugsnag_Notifier_Model_Observer::addUserTab()` does not throw error if `Mage::getSingleton('customer/session')->getCustomer()` is empty

### Observed behavior
PHP Fatal Error: Call to a member function getId() on a non-object

### Steps to reproduce
Bit of a weird one, and hints at an error elsewhere in the stack. It requires `Mage::getSingleton('customer/session')->isLoggedIn()` to return `true` while`Mage::getSingleton('customer/session')->getCustomer()` returns empty.
At this point, calling `Observer::initBugsnag()` will call `::addUserTab()` and throw a fatal error

### Version
`1.0.0` (`v2.0.0` tag)

### Additional information
Alerted via Bugsnag :)

**Comment by luke-belton** [comment]
`bugsnag-magento` has been deprecated.
